### ISSUE TITLE
Are we using any custom cleartool_tty.exe file?

### ISSUE THREAD

**Issue by gargmukku07** [lanfeust69/clearcase-to-git#2]
Giving error while running:- 
../GitImporter.exe -S:fullVobDB.bin -E:to_import.files -D:to_import.dirs -C:$view -O:$refDate -G *.export

**Comment by lanfeust69** [comment]
Yes, cleartool_tty.exe is a patched (hacked ?) version of cleartool.exe.

The original one (due to the unix origins) would only display a prompt when run from a tty. This in practice prevented the use of the same process for more that one command, and creating a process for each command was prohibitively expensive (at least on windows, and for a very big VOB as we had). Since the COM interface was also unusable (hopelessly bugged), I went for a hacked version of cleartool.exe that would always display a prompt when done with a command.

However, cleartool_tty.exe still requires the remaining of clearcase install for the dlls it uses. And of course, these must match the exact same version of cleartool.exe. If there is a mismatch, the included cleartool_tty.exe won't work, and you'll need to either make a similar patch to your own version of cleartool.exe (admittedly not 100% straightforward), or change the clearcase interop to some other solution (the simpler likely being creating a new process for each command, if the performance penalty is acceptable, such as for a rather small VOBs).
